# Hong-Ping : UI.o SignUp.o DropOut.o Login.o Logout.o Enroll.o ListOnSale.o ListSoldOut.o SearchOnSale.o Purchase.o ListPurchaseHistory.o Rate.o CollectStatistics.o Admin.o Member.o Product.o Main.o
# 		g++ -o Hong-Ping UI.o SignUp.o DropOut.o Login.o Logout.o Enroll.o ListOnSale.o ListSoldOut.o SearchOnSale.o Purchase.o ListPurchaseHistory.o Rate.o CollectStatistics.o Admin.o Member.o Product.o Main.o

Hong-Ping : UI.o SignUp.o DropOut.o Login.o Logout.o Enroll.o ListOnSale.o ListSoldOut.o Admin.o Member.o Product.o Main.o
		g++ -o Hong-Ping UI.o SignUp.o DropOut.o Login.o Logout.o Enroll.o ListOnSale.o ListSoldOut.o Admin.o Member.o Product.o Main.o

UI.o : UI.cpp
		g++ -c -o UI.o UI.cpp

SignUp.o : SignUp.cpp
		g++ -c -o SignUp.o SignUp.cpp

DropOut.o : DropOut.cpp
		g++ -c -o DropOut.o DropOut.cpp

Login.o : Login.cpp
		g++ -c -o Login.o Login.cpp

Logout.o : Logout.cpp
		g++ -c -o Logout.o Logout.cpp

Enroll.o : Enroll.cpp
		g++ -c -o Enroll.o Enroll.cpp

ListOnSale.o : ListOnSale.cpp
		g++ -c -o ListOnSale.o ListOnSale.cpp	

ListSoldOut.o : ListSoldOut.cpp
		g++ -c -o ListSoldOut.o ListSoldOut.cpp

# SearchOnSale.o : SearchOnSale.cpp
# 		g++ -c -o SearchOnSale.o SearchOnSale.cpp

# Purchase.o : Purchase.cpp
# 		g++ -c -o Purchase.o Purchase.cpp

# ListPurchaseHistory.o : ListPurchaseHistory.cpp
# 		g++ -c -o ListPurchaseHistory.o ListPurchaseHistory.cpp

# Rate.o : Rate.cpp
# 		g++ -c -o Rate.o Rate.cpp

# CollectStatistics.o : CollectStatistics.cpp
# 		g++ -c -o CollectStatistics.o CollectStatistics.cpp

Admin.o : Admin.cpp
		g++ -c -o Admin.o Admin.cpp

Member.o : Member.cpp
		g++ -c -o Member.o Member.cpp

Product.o : Product.cpp
		g++ -c -o Product.o Product.cpp

Main.o : Main.cpp
		g++ -c -o Main.o Main.cpp

clear :
		rm *.o Hong-Ping output.txt
